# Generated by Django 5.1.3 on 2024-11-12 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=30, null=True, unique=True, verbose_name='Slug-r')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'db_table': 'rubric',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Подрубрика')),
                ('slug', models.SlugField(blank=True, max_length=30, null=True, unique=True, verbose_name='Slug-sr')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subrubrics', to='bboard.rubric', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Подрубрика',
                'verbose_name_plural': 'Подрубрики',
                'db_table': 'subrubric',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Товар')),
                ('content', models.TextField(verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Pазмер скидки')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('slug', models.SlugField(blank=True, max_length=30, null=True, unique=True, verbose_name='Slug-bd')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.rubric', verbose_name='Рубрика')),
                ('subrubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.subrubric', verbose_name='Подрубрика')),
            ],
            options={
                'verbose_name': 'Объяление',
                'verbose_name_plural': 'Объявления',
                'db_table': 'bboard_ads',
                'ordering': ['-published'],
            },
        ),
    ]
